openapi: 3.0.1
info:
  title: credentials-api
  description: REST API documentation for the credentials-api
  version: 1.0.0
servers:
- url: /
paths:
  /v1/participants/{participantContextId}/credentials:
    post:
      tags:
      - Storage API
      description: Writes a set of credentials into storage
      operationId: storeCredential
      parameters:
      - name: participantContextId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialMessage"
      responses:
        "2xx":
          description: The credentialMessage was successfully processed and stored
        "400":
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "401":
          description: No Authorization header was given.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "403":
          description: "The given authentication token could not be validated. This\
            \ can happen, when the request body calls for a broader credentialMessage\
            \ scope than the granted scope in the auth token"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
  /v1/participants/{participantContextId}/offers:
    post:
      tags:
      - Credential Offer API
      description: Notifies the holder about the availability of a particular credential
        for issuance
      operationId: offerCredential
      parameters:
      - name: participantContextId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
              externalDocs:
                description: DCP Credential Offer API
                url: https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol
      responses:
        "200":
          description: The offer notification was successfully received.
        "400":
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "401":
          description: No Authorization header was given.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "403":
          description: The given authentication token could not be validated.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
  /v1/participants/{participantContextId}/presentations/query:
    post:
      tags:
      - Presentation API
      description: "Issues a new presentation query, that contains either a DIF presentation\
        \ definition, or a list of scopes"
      operationId: queryPresentation
      parameters:
      - name: participantContextId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PresentationQueryMessage"
      responses:
        "200":
          description: "The query was successfully processed, the response contains\
            \ the VerifiablePresentation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PresentationResponseMessage"
        "400":
          description: "Request body was malformed, for example when both scope and\
            \ presentationDefinition are given"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "401":
          description: No Authorization header was given.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "403":
          description: "The given authentication token could not be validated. This\
            \ can happen, when the request body calls for a broader query scope than\
            \ the granted scope in the auth token"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "501":
          description: "When the request contained a presentationDefinition object,\
            \ but the implementation does not support it."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
    CredentialContainerSchema:
      type: object
      example:
        credentialType: MembershipCredential
        payload: ""
        format: jwt
    CredentialMessage:
      required:
      - '@context'
      - '@type'
      - credentials
      - requestId
      type: object
      properties:
        '@context':
          type: object
        '@type':
          type: string
        credentials:
          type: array
          items:
            $ref: "#/components/schemas/CredentialContainerSchema"
        requestId:
          type: string
      example:
        '@context':
        - https://w3id.org/dspace-dcp/v1.0/dcp.jsonld
        type: CredentialMessage
        credentials:
        - credentialType: MembershipCredential
          payload: ""
          format: jwt
        - credentialType: OrganizationCredential
          payload: ""
          format: json-ld
        requestId: requestId
    JsonObject:
      type: object
      properties:
        empty:
          type: boolean
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
      additionalProperties:
        $ref: "#/components/schemas/JsonValue"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    PresentationDefinitionSchema:
      type: object
      example: |
        {
          "comment": "taken from https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition"
          "presentationDefinition": {
            "id": "first simple example",
            "input_descriptors": [
              {
                "id": "A specific type of VC",
                "name": "A specific type of VC",
                "purpose": "We want a VC of this type",
                "constraints": {
                  "fields": [
                    {
                      "path": [
                        "$.type"
                      ],
                      "filter": {
                        "type": "string",
                        "pattern": "<the type of VC e.g. degree certificate>"
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
    PresentationQueryMessage:
      required:
      - '@context'
      - '@type'
      type: object
      properties:
        '@context':
          type: object
        '@type':
          type: string
        presentationDefinition:
          $ref: "#/components/schemas/PresentationDefinitionSchema"
        scope:
          type: array
          items:
            type: string
      example:
        '@context':
        - https://w3id.org/tractusx-trust/v0.8
        - https://identity.foundation/presentation-exchange/submission/v1
        '@type': PresentationQueryMessage
        presentationDefinition: null
        scope:
        - org.eclipse.edc.vc.type:SomeCredential_0.3.5:write
        - org.eclipse.edc.vc.type:SomeOtherCredential:read
        - org.eclipse.edc.vc.type:ThirdCredential:*
    PresentationResponseMessage:
      required:
      - '@context'
      - presentation
      type: object
      properties:
        '@context':
          type: object
        presentation:
          type: array
          items:
            type: object
            anyOf:
            - type: string
            - $ref: "#/components/schemas/JsonObject"
      example:
        '@context':
        - https://w3id.org/tractusx-trust/v0.8
        '@type': PresentationResponseMessage
        presentation:
        - dsJdh...UMetV
  securitySchemes:
    Authentication:
      type: http
      description: Self-Issued ID
      scheme: bearer
      bearerFormat: JWT
