openapi: 3.0.1
info:
  title: sts-api
  description: REST API documentation for the sts-api
  license:
    name: "The Apache License, Version 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  version: 0.15.0-SNAPSHOT
servers:
- url: /
paths:
  /token:
    post:
      tags:
      - Secure Token Service Api
      operationId: token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/token_request"
            encoding:
              audience:
                style: form
              bearer_access_scope:
                style: form
              client_id:
                style: form
              client_secret:
                style: form
              grant_type:
                style: form
              token:
                style: form
      responses:
        "200":
          description: The Self-Issued ID token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StsTokenResponse"
        "400":
          description: Invalid Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StsTokenErrorResponse"
components:
  schemas:
    StsTokenResponse:
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
          format: int64
        token_type:
          type: string
    StsTokenErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
    token_request:
      required:
      - audience
      - client_id
      - client_secret
      - grant_type
      type: object
      properties:
        audience:
          type: string
          description: Audience for the SI token
        bearer_access_scope:
          type: string
          description: Scope to be added in the VP token
        client_id:
          type: string
          description: Id of the client requesting an SI token
        client_secret:
          type: string
          description: Secret of the client requesting an SI token
        grant_type:
          type: string
          description: "Type of grant: must be set to client_credentials"
        token:
          type: string
          description: VP token to be added as a claim in the SI token
