openapi: 3.0.1
info:
  description: This represents the Credential Request API as per DCP specification.
    It serves endpoints to request the issuance of Verifiable Credentials from an
    issuer.
  title: Credential Request API
  version: v1alpha
paths:
  /v1alpha/credentials:
    post:
      description: Requests the issuance of one or several verifiable credentials
        from an issuer
      operationId: requestCredentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialRequestMessage"
      responses:
        "201":
          description: The request was successfully received and is being processed.
          headers:
            Location:
              description: contains the relative URL where the status of the request
                can be queried (Credential Request Status API)
              style: simple
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, e.g. required parameter or properties\
            \ were missing"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: No Authorization header was provided.
        "403":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: The given authentication token could not be validated or the
            client is not authorized to call this endpoint.
      tags:
      - Credential Request API
components:
  schemas:
    ApiErrorDetail:
      type: object
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
    CredentialRequest:
      type: object
      properties:
        credentialType:
          type: string
        format:
          type: string
        payload:
          type: object
    CredentialRequestMessage:
      type: object
      properties:
        contexts:
          type: array
          items:
            type: string
        credentials:
          type: array
          items:
            $ref: "#/components/schemas/CredentialRequest"
        type:
          type: string
  securitySchemes:
    Authentication:
      bearerFormat: JWT
      description: Self-Issued ID token containing an access_token
      scheme: bearer
      type: http
