name: "Setup Gradle"
description: "Setup Gradle"
runs:
  using: "composite"
  steps:
    # Install Java and cache MVD Gradle build.
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
