name: publish openapi ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: eclipse-edc/.github/.github/workflows/publish-openapi-ui.yml@main
    secrets: inherit
