name: Scan Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pull-request-title:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles conventional commit syntax (https://www.conventionalcommits.org/en/v1.0.0/)
          # (online tool for regex quick check: https://regex101.com/r/V5J8kh/1)
          #
          # Valid examples would be
          # - fix: resolve minor issue
          # - docs(Sample5): update docs for configuration
          # - feat(management-api)!: change path to access contract agreements
          #
          # Invalid examples would be
          # - Add cool feature
          # - Feature/some cool improvement
          # - fix: resolve minor issue.
          regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+((,|\/|\\)?\s?\w+)+\))?!?: [\S ]{1,80}[^\.]$'
          allowed_prefixes: 'build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test'
          prefix_case_sensitive: true
