openapi: 3.0.1
info:
  title: storage-api
  description: REST API documentation for the storage-api
  version: 0.0.1
servers:
- url: /
paths:
  /v1alpha/participants/{participantContextId}/credentials:
    post:
      tags:
      - Storage API
      description: Writes a set of credentials into storage
      operationId: storeCredential
      parameters:
      - name: participantContextId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialMessage"
      responses:
        "2xx":
          description: The credentialMessage was successfully processed and stored
        "400":
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "401":
          description: No Authorization header was given.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "403":
          description: "The given authentication token could not be validated. This\
            \ can happen, when the request body calls for a broader credentialMessage\
            \ scope than the granted scope in the auth token"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
    CredentialContainerSchema:
      type: object
      example:
        credentialType: MembershipCredential
        payload: ""
        format: jwt
    CredentialMessage:
      required:
      - '@context'
      - '@type'
      - credentials
      - requestId
      type: object
      properties:
        '@context':
          type: object
        '@type':
          type: string
        credentials:
          type: array
          items:
            $ref: "#/components/schemas/CredentialContainerSchema"
        requestId:
          type: string
      example:
        '@context':
        - https://w3id.org/dspace-dcp/v1.0/dcp.jsonld
        type: CredentialMessage
        credentials:
        - credentialType: MembershipCredential
          payload: ""
          format: jwt
        - credentialType: OrganizationCredential
          payload: ""
          format: json-ld
        requestId: requestId
    JsonObject:
      type: object
      properties:
        empty:
          type: boolean
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
      additionalProperties:
        $ref: "#/components/schemas/JsonValue"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
  securitySchemes:
    Authentication:
      type: http
      description: Self-Issued ID token containing an access_token
      scheme: bearer
      bearerFormat: JWT
